/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample;


import nu.studer.sample.tables.HibernateSequence;
import nu.studer.sample.tables.Tweet;


/**
 * Convenience access to all tables in bbs_test
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bbs_test.hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>bbs_test.tweet</code>.
     */
    public static final Tweet TWEET = Tweet.TWEET;
}
