/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tweet implements Serializable {

    private static final long serialVersionUID = 333327128;

    private final Integer id;
    private final String  name;
    private final String  text;

    public Tweet(Tweet value) {
        this.id = value.id;
        this.name = value.name;
        this.text = value.text;
    }

    public Tweet(
        Integer id,
        String  name,
        String  text
    ) {
        this.id = id;
        this.name = name;
        this.text = text;
    }

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public String getText() {
        return this.text;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tweet (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(text);

        sb.append(")");
        return sb.toString();
    }
}
