/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import nu.studer.sample.tables.Tweet;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TweetRecord extends UpdatableRecordImpl<TweetRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -1068605285;

    /**
     * Setter for <code>bbs_test.tweet.id</code>.
     */
    public TweetRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>bbs_test.tweet.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bbs_test.tweet.name</code>.
     */
    public TweetRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>bbs_test.tweet.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bbs_test.tweet.text</code>.
     */
    public TweetRecord setText(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>bbs_test.tweet.text</code>.
     */
    public String getText() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Tweet.TWEET.ID;
    }

    @Override
    public Field<String> field2() {
        return Tweet.TWEET.NAME;
    }

    @Override
    public Field<String> field3() {
        return Tweet.TWEET.TEXT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getText();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getText();
    }

    @Override
    public TweetRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TweetRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TweetRecord value3(String value) {
        setText(value);
        return this;
    }

    @Override
    public TweetRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TweetRecord
     */
    public TweetRecord() {
        super(Tweet.TWEET);
    }

    /**
     * Create a detached, initialised TweetRecord
     */
    public TweetRecord(Integer id, String name, String text) {
        super(Tweet.TWEET);

        set(0, id);
        set(1, name);
        set(2, text);
    }
}
